#!/usr/bin/env bash
# lib/40_fastlane.sh — Tự động setup Fastlane + ASC API action
#
# Biến đầu vào (từ project config):
#   PROJECT_ROOT, APP_ID, APP_NAME, FL_APP_LANGUAGE

# --------------------------------------------------------------------------- #
# Tạo Gemfile
# --------------------------------------------------------------------------- #
_fl_create_gemfile() {
  local gemfile="${PROJECT_ROOT}/Gemfile"

  if [[ -f "$gemfile" ]] && grep -q 'fastlane' "$gemfile"; then
    log_ok "Gemfile đã chứa fastlane"
    if ! grep -q 'gem "json"' "$gemfile"; then
      log_info "Auto-patch: Thêm gem json >= 2.7.2 vào Gemfile cũ và xoá lockfile"
      echo 'gem "json", ">= 2.7.2"' >> "$gemfile"
      rm -f "${PROJECT_ROOT}/Gemfile.lock"
    fi
    return
  fi

  [[ -f "$gemfile" ]] && backup_file "$gemfile"
  log_info "Tạo Gemfile..."

  cat > "$gemfile" << 'EOF'
source "https://rubygems.org"

gem "fastlane", ">= 2.220.0"
gem "jwt",      ">= 2.7.0"
gem "json",     "~> 2.7.2"

plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
EOF
  log_ok "Gemfile đã được tạo"
}

# --------------------------------------------------------------------------- #
# Tạo fastlane/Appfile
# --------------------------------------------------------------------------- #
_fl_create_appfile() {
  local appfile="${PROJECT_ROOT}/fastlane/Appfile"
  mkdir -p "${PROJECT_ROOT}/fastlane"

  [[ -f "$appfile" ]] && { log_ok "Appfile đã tồn tại"; return; }

  log_info "Tạo fastlane/Appfile..."
  cat > "$appfile" << EOF
# Appfile — ${APP_NAME}
# Đọc từ biến môi trường CI/CD
app_identifier(ENV["APP_BUNDLE_ID"] || "${APP_ID}")
apple_id(ENV["APPLE_ID"] || "")
# team_id là Apple Developer Portal Team ID (ví dụ: ATVBX8XSBD)
team_id(ENV["APPLE_TEAM_ID"] || "")
# itc_team_id là App Store Connect Team ID (ví dụ: 126561332)
itc_team_id(ENV["ITC_TEAM_ID"] || "")
EOF
  log_ok "fastlane/Appfile đã được tạo"
}


# --------------------------------------------------------------------------- #
# Tạo fastlane/Fastfile — render từ biến PROJECT_ROOT, APP_ID, APP_NAME, v.v.
# --------------------------------------------------------------------------- #
_fl_create_fastfile() {
  local fastfile="${PROJECT_ROOT}/fastlane/Fastfile"
  [[ -f "$fastfile" ]] && { 
    log_ok "Fastfile đã tồn tại"

    return
  }

  log_info "Tạo fastlane/Fastfile..."

  # Dùng process substitution để expand biến shell vào nội dung Fastfile
  cat > "$fastfile" << FFEOF
# =============================================================================
# Fastfile — ${APP_NAME}
# Auto-generated by mobile-ci service
#
# Lanes:
#   bundle exec fastlane create_app         → Tạo app trên App Store Connect
#   bundle exec fastlane setup_signing      → Tạo cert + provisioning (match)
#   bundle exec fastlane build_ios          → Build IPA (gym)
#   bundle exec fastlane release_testflight → Upload TestFlight (pilot)
#   bundle exec fastlane full_setup         → Toàn bộ flow lần đầu
#   bundle exec fastlane ci_pipeline        → CI/CD tự động
#
# Biến môi trường bắt buộc (xem .env của Runner / .env.runner.example):
#   ASC_KEY_ID, ASC_ISSUER_ID, ASC_PRIVATE_KEY_CONTENT
#   APP_BUNDLE_ID, APP_NAME, APPLE_ID, APPLE_TEAM_ID
# =============================================================================

require "json"
require "base64"
require "time"
require "open3"
require "tempfile"
require "net/http"
require "uri"
require "cgi"
require "openssl"
require "jwt"

# ── Auto-load mobile.config.sh vào ENV ──────────────────────────────────────
# Fastlane (Ruby) không tự source bash file. Đoạn này tự tìm và source
# mobile.config.sh, import các biến cần thiết vào ENV để mọi lane dùng được.
# Thứ tự ưu tiên path: MOBILE_CONFIG_PATH env > project_root > ../mobile-ci/.
_mobile_config_candidates = [
  ENV["MOBILE_CONFIG_PATH"],
  File.expand_path("../mobile.config.sh", __dir__),
  File.expand_path("../../mobile-ci/mobile.config.sh", __dir__),
].compact
_mobile_config_path = _mobile_config_candidates.find { |p| File.exist?(p) }

if _mobile_config_path
  UI.message("📋 Load mobile config: #{_mobile_config_path}") if defined?(UI)
  %w[TESTFLIGHT_TESTERS APP_VERSION APP_BUNDLE_ID FL_APP_LANGUAGE FL_APP_SKU].each do |_var|
    next if ENV[_var] && !ENV[_var].strip.empty?
    _out, _, _status = Open3.capture3('bash', '-c',
      %(source "#{_mobile_config_path}" >/dev/null 2>&1 && printf "%s" "\${#{_var}:-}"))
    ENV[_var] = _out if _status.success? && !_out.empty?
  end
end

before_all do
  setup_ci if ENV["CI"]
  # Global register ASC API key for all actions (including Xcode automatic signing)
  app_store_connect_api_key(**asc_api_key)
end

# Load App Store Connect API Key ─────────────────────────────────────────────────
def asc_api_key
  content = ENV["ASC_PRIVATE_KEY_CONTENT"]
  # Nếu base64-encoded (thường dùng trong CI/CD secrets)
  content = Base64.decode64(content) if content && !content.include?("-----BEGIN")
  if content.nil? || content.strip.empty?
    path = ENV["ASC_PRIVATE_KEY_PATH"] || "fastlane/asc_private_key.p8"
    UI.user_error!("ASC private key không tìm thấy: #{path}") unless File.exist?(path)
    content = File.read(path)
  end
  {
    key_id:               ENV["ASC_KEY_ID"]    || UI.user_error!("Thiếu ASC_KEY_ID"),
    issuer_id:            ENV["ASC_ISSUER_ID"] || UI.user_error!("Thiếu ASC_ISSUER_ID"),
    key_content:          content,
    is_key_content_base64: false,
    duration:             1200,
    in_house:             false,
  }
end

# ─────────────────────────────────────────────────────────────────────────────
# Helpers gọi App Store Connect REST API trực tiếp (port từ Node.js script).
# ─────────────────────────────────────────────────────────────────────────────
def asc_jwt
  key = asc_api_key
  now = Time.now.to_i
  payload = {
    iss: key[:issuer_id],
    iat: now,
    exp: now + 600,
    aud: "appstoreconnect-v1",
  }
  headers = { kid: key[:key_id], typ: "JWT" }
  pk = OpenSSL::PKey.read(key[:key_content])
  JWT.encode(payload, pk, "ES256", headers)
end

def asc_api(method, path, body = nil)
  uri = URI("https://api.appstoreconnect.apple.com/v1/#{path}")
  req_class = {
    "GET"    => Net::HTTP::Get,
    "POST"   => Net::HTTP::Post,
    "DELETE" => Net::HTTP::Delete,
  }[method.to_s.upcase] || raise("Unsupported method: #{method}")
  req = req_class.new(uri.request_uri)
  req["Authorization"] = "Bearer #{asc_jwt}"
  req["Content-Type"]  = "application/json"
  req.body = JSON.dump(body) if body

  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true
  resp = http.request(req)
  parsed = (JSON.parse(resp.body) rescue nil)
  [resp.code.to_i, parsed, resp.body]
end

def asc_error_detail(parsed, raw)
  (parsed && parsed["errors"] && parsed["errors"].first && parsed["errors"].first["detail"]) || raw
end

def asc_find_app_id(bundle_id)
  code, data, body = asc_api(:get, "apps?filter%5BbundleId%5D=#{CGI.escape(bundle_id)}")
  UI.user_error!("List apps fail HTTP #{code}: #{body}") unless code == 200
  app = (data["data"] || []).first
  UI.user_error!("App với bundle '#{bundle_id}' chưa tồn tại trên ASC") unless app
  app["id"]
end

def asc_get_or_create_group(app_id, group_name)
  code, data, body = asc_api(:get, "betaGroups?filter%5Bapp%5D=#{app_id}")
  UI.user_error!("List groups fail HTTP #{code}: #{body}") unless code == 200

  existing = (data["data"] || []).find { |g| g.dig("attributes", "name") == group_name }
  if existing
    UI.success("✅ Group '#{group_name}' đã tồn tại (id=#{existing["id"]})")
    return existing["id"]
  end

  UI.important("⚠️  Group '#{group_name}' chưa có → tạo mới...")
  ccode, cdata, cbody = asc_api(:post, "betaGroups", {
    data: {
      type: "betaGroups",
      attributes: { name: group_name, isInternalGroup: false },
      relationships: { app: { data: { type: "apps", id: app_id } } },
    },
  })
  UI.user_error!("Create group fail HTTP #{ccode}: #{cbody}") unless [200, 201].include?(ccode)
  group_id = cdata["data"]["id"]
  UI.success("✅ Đã tạo group '#{group_name}' (id=#{group_id})")
  group_id
end

def asc_assign_latest_build_and_submit(app_id, group_id)
  code, data, body = asc_api(:get, "builds?filter%5Bapp%5D=#{app_id}&sort=-uploadedDate&limit=1")
  unless code == 200
    UI.important("⚠️ Không lấy được builds: HTTP #{code}: #{body}")
    return nil
  end

  build = (data["data"] || []).first
  unless build
    UI.message("ℹ️ Không có build nào trên ASC")
    return nil
  end

  build_id = build["id"]
  version  = build.dig("attributes", "version")
  state    = build.dig("attributes", "processingState")
  uploaded = build.dig("attributes", "uploadedDate")
  UI.message("📦 Latest build: #{version} (#{state}) — uploaded #{uploaded.to_s.slice(0, 10)}")

  if state != "VALID"
    UI.important("⏳ Build chưa VALID (state=#{state}) → bỏ qua assign + submit, chạy lại lane này sau ~5-15 phút")
    return nil
  end

  acode, _adata, abody = asc_api(:post, "betaGroups/#{group_id}/relationships/builds",
    { data: [{ type: "builds", id: build_id }] })
  if acode.between?(200, 299)
    UI.success("✅ Assigned build #{version} vào group")
  else
    detail = asc_error_detail((JSON.parse(abody) rescue nil), abody).to_s
    if detail.include?("already")
      UI.message("ℹ️ Build #{version} đã được assign trước đó")
    else
      UI.important("⚠️ Assign build fail HTTP #{acode}: #{detail}")
    end
  end

  scode, _sdata, sbody = asc_api(:post, "betaAppReviewSubmissions", {
    data: {
      type: "betaAppReviewSubmissions",
      relationships: { build: { data: { type: "builds", id: build_id } } },
    },
  })
  if scode.between?(200, 299)
    UI.success("✅ Submitted build #{version} cho Beta App Review")
  else
    parsed = (JSON.parse(sbody) rescue nil)
    detail = asc_error_detail(parsed, sbody).to_s
    err_code = parsed && parsed["errors"] && parsed["errors"].first && parsed["errors"].first["code"]
    if err_code == "ENTITY_UNPROCESSABLE-RELATIONSHIP" || detail.include?("already submitted") || detail.include?("in review")
      UI.message("ℹ️ Build đã được submit hoặc đang trong quá trình review")
    elsif detail.include?("missing")
      UI.important("⚠️ Submit fail: thiếu Test Information (What to Test, Export Compliance...) — điền trên ASC web trước")
    else
      UI.important("⚠️ Submit Beta Review fail HTTP #{scode}: #{detail}")
    end
  end

  build_id
end

def asc_add_tester(group_id, email)
  lcode, ldata, lbody = asc_api(:get, "betaTesters?filter%5Bemail%5D=#{CGI.escape(email)}")
  return [false, "lookup HTTP #{lcode}: #{lbody}"] unless lcode == 200
  existing = (ldata["data"] || []).first

  if existing
    rcode, _rd, rbody = asc_api(:post, "betaGroups/#{group_id}/relationships/betaTesters",
      { data: [{ type: "betaTesters", id: existing["id"] }] })
    return [true, "linked existing"] if rcode.between?(200, 299)
    detail = asc_error_detail((JSON.parse(rbody) rescue nil), rbody)
    return [false, "attach HTTP #{rcode}: #{detail}"]
  end

  ccode, _cd, cbody = asc_api(:post, "betaTesters", {
    data: {
      type: "betaTesters",
      attributes: {
        email:     email,
        firstName: email.split("@").first,
        lastName:  "Tester",
      },
      relationships: {
        betaGroups: { data: [{ type: "betaGroups", id: group_id }] },
      },
    },
  })
  return [true, "created + added"] if ccode.between?(200, 299)
  detail = asc_error_detail((JSON.parse(cbody) rescue nil), cbody)
  [false, "create HTTP #{ccode}: #{detail}"]
end

# ── LANE: create_app ─────────────────────────────────────────────────────────
lane :create_app do |opts|
  UI.header("📱 Tạo App trên App Store Connect")
  bundle_id = opts[:bundle_id] || ENV["APP_BUNDLE_ID"] || "${APP_ID}"
  app_name  = opts[:app_name]  || ENV["APP_NAME"]      || "${APP_NAME}"
  sku       = opts[:sku]       || ENV["APP_SKU"]        || bundle_id.gsub(".", "-")
  language  = opts[:language]  || ENV["APP_LANGUAGE"]   || "${FL_APP_LANGUAGE:-English}"

  # ── Bước 1: Check app đã tồn tại chưa qua ASC API Key ──
  key = asc_api_key
  api_key_result = app_store_connect_api_key(
    key_id:                key[:key_id],
    issuer_id:             key[:issuer_id],
    key_content:           key[:key_content],
    is_key_content_base64: false,
    duration:              1200,
    in_house:              false,
  )
  Spaceship::ConnectAPI.token = Spaceship::ConnectAPI::Token.from(hash: api_key_result)

  existing_app = Spaceship::ConnectAPI::App.find(bundle_id)
  if existing_app
    UI.success("✅ App đã tồn tại trên ASC: #{bundle_id} (#{existing_app.name})")
    next
  end

  UI.important("App chưa tồn tại, tiến hành tạo mới...")

  # ── Bước 2: Cần FASTLANE_SESSION để tạo app mới ──
  unless ENV["FASTLANE_SESSION"] && !ENV["FASTLANE_SESSION"].empty?
    UI.error("⚠️  Không có FASTLANE_SESSION!")
    UI.error("👉 Chạy lệnh sau trên máy local rồi copy vào CI secret:")
    UI.error("   bundle exec fastlane spaceauth -u #{ENV["APPLE_ID"] || "your@apple.com"}")
    UI.error("   Sau đó set FASTLANE_SESSION=<giá trị vừa copy>")
    UI.error("   Lưu ý: Session hết hạn sau vài tuần, cần renew định kỳ")
    UI.user_error!("Thiếu FASTLANE_SESSION để tạo app mới.")
  end

  UI.important("🔑 Dùng FASTLANE_SESSION để tạo app...")

  # ── Bước 3: Thử tạo app, fallback tên nếu bị trùng ──
  begin
    create_app_online(
      username:       ENV["APPLE_ID"],
      app_identifier: bundle_id,
      app_name:       app_name,
      language:       language,
      sku:            sku,
      platform:       "ios",
      team_name:      ENV["APPLE_TEAM_NAME"] || "",
      itc_team_name:  ENV["ITC_TEAM_NAME"]   || ENV["APPLE_TEAM_NAME"] || "",
      skip_itc:       false,
      skip_devcenter: false,
    )
    UI.success("✅ App '#{app_name}' tạo thành công!")

  rescue => e
    if e.message.include?("The app name you entered is already being used") ||
       e.message.include?("already taken")
      suffix    = SecureRandom.hex(3)
      new_name  = "#{app_name} (#{suffix})"
      UI.important("⚠️  Tên '#{app_name}' đã bị dùng → thử tên '#{new_name}'")

      create_app_online(
        username:       ENV["APPLE_ID"],
        app_identifier: bundle_id,
        app_name:       new_name,
        language:       language,
        sku:            sku,
        platform:       "ios",
        team_name:      ENV["APPLE_TEAM_NAME"] || "",
        itc_team_name:  ENV["ITC_TEAM_NAME"]   || ENV["APPLE_TEAM_NAME"] || "",
        skip_itc:       false,
        skip_devcenter: false,
      )
      UI.success("✅ App '#{new_name}' tạo thành công!")
      UI.important("💡 Đổi tên thật tại: https://appstoreconnect.apple.com")
    else
      raise e
    end
  end
end

# ── LANE: setup_signing ──────────────────────────────────────────────────────
lane :setup_signing do |opts|
  UI.header("🔑 Setup Code Signing (Match)")

  git_url = ENV["MATCH_GIT_URL"]
  if git_url.nil? || git_url.empty?
    UI.user_error!("Thiếu MATCH_GIT_URL! Vui lòng cấu hình biến môi trường hoặc GitHub Secret MATCH_GIT_URL.")
  end

  # Match đọc MATCH_PASSWORD từ env tự động
  key = asc_api_key
  api_key_result = app_store_connect_api_key(
    key_id:         key[:key_id],
    issuer_id:      key[:issuer_id],
    key_content:    key[:key_content],
    is_key_content_base64: false,
    duration:       1200,
    in_house:       false,
  )

  match(
    type:                  opts[:type] || ENV["MATCH_TYPE"] || "appstore",
    app_identifier:        opts[:bundle_id] || ENV["APP_BUNDLE_ID"] || "${APP_ID}",
    git_url:               git_url,
    git_branch:            ENV["MATCH_GIT_BRANCH"] || "main",
    readonly:              ENV["CI"] ? true : false,
    clone_branch_directly: true,
    force_for_new_devices: !ENV["CI"],
    api_key:               api_key_result,
  )
  UI.success("✅ Code signing xong (type=#{opts[:type] || 'appstore'})")
end

# ── LANE: build_ios ──────────────────────────────────────────────────────────
lane :build_ios do |opts|
  UI.header("🏗️  Build iOS IPA")
  bundle_id = opts[:bundle_id] || ENV["APP_BUNDLE_ID"] || "${APP_ID}"

  if ENV["MATCH_GIT_URL"].nil? || ENV["MATCH_GIT_URL"].empty?
    UI.important("⚠️ Bỏ qua setup_signing vì MATCH_GIT_URL trống. Sẽ cố gắng build Xcode mà không dùng Match...")
    UI.important("👉 Bật Automatically manage signing trong Xcode project...")
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "ios/App/App.xcodeproj",
      team_id: ENV["APPLE_TEAM_ID"]
    )
  else
    # Tắt Auto Signing nếu đang dùng Match
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj"
    )
    setup_signing(bundle_id: bundle_id, type: "appstore") unless opts[:skip_signing]
  end

  export_opts = {}
  if ENV["MATCH_GIT_URL"] && !ENV["MATCH_GIT_URL"].empty?
    export_opts = { provisioningProfiles: { bundle_id => "match AppStore #{bundle_id}" } }
  end

  xc_args = []
  if ENV["APPLE_TEAM_ID"] && !ENV["APPLE_TEAM_ID"].empty?
    xc_args << "DEVELOPMENT_TEAM=#{ENV["APPLE_TEAM_ID"]}"
  end

  if ENV["MATCH_GIT_URL"].nil? || ENV["MATCH_GIT_URL"].empty?
    xc_args << "-allowProvisioningUpdates"
  end

  xc_args_str = xc_args.join(" ")
  xc_args_str = nil if xc_args_str.empty?

  workspace_path = "ios/App/App.xcworkspace"
  project_path = "ios/App/App.xcodeproj"
  
  gym_options = {
    scheme:            opts[:scheme] || ENV["IOS_SCHEME"] || "App",
    configuration:     opts[:config] || ENV["BUILD_CONFIG"] || "Release",
    export_method:     "app-store",
    output_directory:  "build",
    output_name:       "App.ipa",
    clean:             true,
    include_symbols:   true,
    include_bitcode:   false,
    xcargs:            xc_args_str,
    export_options:    export_opts,
  }

  if Dir.exist?(workspace_path)
    gym_options[:workspace] = workspace_path
  else
    gym_options[:project] = project_path
  end

  gym(**gym_options)
  UI.success("✅ Build xong: build/App.ipa")
end

# ── LANE: release_testflight ─────────────────────────────────────────────────
lane :release_testflight do |opts|
  UI.header("🚀 Upload lên TestFlight")

  key = asc_api_key
  api_key_result = app_store_connect_api_key(
    key_id:                key[:key_id],
    issuer_id:             key[:issuer_id],
    key_content:           key[:key_content],
    is_key_content_base64: false,
    duration:              1200,
    in_house:              false,
  )

  pilot(
    api_key:                           api_key_result,
    ipa:                               opts[:ipa_path] || "build/App.ipa",
    skip_waiting_for_build_processing: true,
    distribute_external:               false,
    notify_external_testers:           true,
    changelog:                         opts[:changelog] || ENV["RELEASE_NOTES"] || "Build mới",
    beta_app_description:              "${APP_NAME}",
    beta_app_review_info: {
      contact_email: "dita.vo@metacrew.vn",
      contact_first_name: "DEV",
      contact_last_name: "Meta",
      contact_phone: "+84981531110",
      demo_account_required: false,
    },
  )
  UI.success("✅ Upload TestFlight + distribute cho External Testers thành công!")

  # ── Post-upload: Quản lý External Testers qua ASC REST API trực tiếp ────────
  # Port flow từ Node.js script (manage_testflight_testers.js): tất cả gọi
  # endpoint public trong App Store Connect API docs, tránh dùng `pilot add`
  # CLI vốn hit endpoint `bulkBetaTesterAssignments` đã chết.
  bundle_id  = opts[:bundle_id] || ENV["APP_BUNDLE_ID"] || "${APP_ID}"
  group_name = opts[:group]     || ENV["TESTFLIGHT_GROUP"] || "External Testers"

  UI.header("📡 ASC API: lookup app + group")
  app_id   = asc_find_app_id(bundle_id)
  group_id = asc_get_or_create_group(app_id, group_name)

  UI.header("📦 Assign latest build + submit Beta Review")
  asc_assign_latest_build_and_submit(app_id, group_id)

  testers_env = ENV["TESTFLIGHT_TESTERS"].to_s.strip
  if testers_env.empty?
    UI.message("ℹ️ TESTFLIGHT_TESTERS rỗng → bỏ qua bước add testers")
  else
    UI.header("👥 Add External Testers")
    emails = testers_env.split(/[,\n\r\s]+/).map(&:strip).reject(&:empty?)
    UI.message("📧 #{emails.length} email(s) sẽ được add vào '#{group_name}': #{emails.join(', ')}")

    emails.each do |email|
      ok, info = asc_add_tester(group_id, email)
      if ok
        UI.success("✅ #{email} (#{info})")
      else
        UI.important("⚠️ #{email}: #{info}")
      end
      sleep(0.3) # rate-limit an toàn (tương đương sleep(300) trong JS)
    end
  end
end

# ── LANE: full_setup ─────────────────────────────────────────────────────────
lane :full_setup do |opts|
  UI.header("🎬 Full Setup — ${APP_NAME}")
  bundle_id = opts[:bundle_id] || ENV["APP_BUNDLE_ID"] || "${APP_ID}"
  app_name  = opts[:app_name]  || ENV["APP_NAME"]      || "${APP_NAME}"

  create_app(bundle_id: bundle_id, app_name: app_name)

  if ENV["MATCH_GIT_URL"] && !ENV["MATCH_GIT_URL"].empty?
    setup_signing(bundle_id: bundle_id, type: "development")
    setup_signing(bundle_id: bundle_id, type: "appstore")
  else
    UI.important("Bỏ qua setup_signing (MATCH_GIT_URL chưa có)")
  end
  UI.success("🎉 Full setup hoàn tất!")
end

# ── LANE: ci_pipeline ────────────────────────────────────────────────────────
lane :ci_pipeline do
  UI.header("⚙️  CI Pipeline — ${APP_NAME}")
  create_app         unless ENV["SKIP_ASC_SETUP"] == "true"
  build_ios          unless ENV["SKIP_BUILD"]     == "true"
  release_testflight(
    changelog: ENV["RELEASE_NOTES"] || "CI build - \#{Time.now.strftime('%Y-%m-%d %H:%M')}",
  ) unless ENV["SKIP_UPLOAD"] == "true"
end

error do |lane, exception|
  UI.error("❌ Lane '#{lane}' lỗi: #{exception.message}")
  if ENV["SLACK_WEBHOOK_URL"] && !ENV["SLACK_WEBHOOK_URL"].empty?
    slack(
      message: "❌ ${APP_NAME} build lỗi: #{exception.message}",
      slack_url: ENV["SLACK_WEBHOOK_URL"],
      success: false,
      default_payloads: [:lane, :git_branch, :git_author],
    )
  end
end
FFEOF
  log_ok "fastlane/Fastfile đã được tạo"
}

# --------------------------------------------------------------------------- #
# Chạy bundle install
# --------------------------------------------------------------------------- #
_fl_bundle_install() {
  log_section "Bundle Install"
  cd "$PROJECT_ROOT"

  # Đảm bảo bundler có sẵn
  ensure_cmd bundle || { log_warn "Bỏ qua bundle install (bundler không có)"; return; }

  if bundle check &>/dev/null 2>&1; then
    log_ok "Gems đã đầy đủ"
    return
  fi

  log_info "Chạy bundle install..."
  bundle install --jobs=4 --retry=3
  log_ok "bundle install hoàn tất"
}

# --------------------------------------------------------------------------- #
# Hàm tổng: setup_fastlane
# Chỉ chạy khi có ít nhất 1 platform được add
# --------------------------------------------------------------------------- #
run_fastlane_setup() {
  if [[ "${SKIP_FASTLANE:-false}" == "true" ]]; then
    log_skip "SKIP_FASTLANE=true → Bỏ qua Fastlane"
    return
  fi

  # Kiểm tra có platform nào chưa
  if [[ ! -d "${PROJECT_ROOT}/ios" ]] && [[ ! -d "${PROJECT_ROOT}/android" ]]; then
    log_skip "Chưa có platform nào (ios/ hoặc android/) → Bỏ qua Fastlane"
    log_info "Đặt PLATFORMS=\"ios\" hoặc \"android\" để kích hoạt"
    return
  fi

  log_section "Fastlane Setup"

  if ! check_ruby; then
    log_warn "Bỏ qua Fastlane (Ruby chưa được cài)"
    return
  fi

  _fl_create_gemfile
  _fl_create_appfile
  _fl_create_fastfile
  _fl_bundle_install

  log_ok "Fastlane setup hoàn tất!"
}
