# Android Release Keystore Properties
# Tạo bởi mobile-ci
#
# ⚠️ KHÔNG commit file này nếu chứa password thật!
# Trên CI/CD: dùng env vars KEYSTORE_PASSWORD, KEYSTORE_ALIAS
storeFile=release-keystore.jks
storePassword=89inLL1BhtWR8guGdBue
keyAlias=release
keyPassword=89inLL1BhtWR8guGdBue
